[project]
name = "gabarito-solver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.13.0.90",
    "pandas>=3.0.0",
    "pytesseract>=0.3.13",
]
